cargo-features = ["edition"]
[package]
name = "fshash"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = '2018'

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
rust-crypto = "0.2.36"
log = "0.4.3"
